### PR TITLE
add physiographic provinces to layers and to story

### PR DESCRIPTION
**Pull request by mhines-usgs**
Before making a pull request
----------------------------
First . . .
- [ ] Clean the code the way Vue likes it - run 'npm run lint --fix'        
- [ ] Make sure all tests run

Then check for accessibly compliance
- [ ] Run WAVE plugin 508 compliance tool

Then run Browserstack; check that application works on . . .
- [ ] Chrome
- [ ] Safari
- [ ] Edge
- [ ] Firefox
- [ ] Samsung Internet
- [ ] Internet Explorer 11 (not supported, but still needs at least a working user redirect page)

Finally . . .
- [ ] Update the changelog appropriately

Title
-----------
add physiographic provinces to the map

Description
-----------
add the provinces to the layers
style their display
create a chapter

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the ticket
- [ ] Assign someone to review unless the change is trivial

### CODE REVIEW

**Comment by mhines-usgs** [comment]
looks like the 🍨 Aaron wanted
image

**Review by mwernimont — APPROVED** [review]
That adds some pizzaz to the map

**Comment by mhines-usgs** [comment]
One thing I'm not sure about, because this is a polygon layer, there really isn't a tour, but I don't know how to remove that button. I tried removing the entire line https://github.com/usgs-makerspace/delaware-basin-tour/pull/27/files#diff-2e89e7f5e64419e57aeb3fa89023d8d1R166 there, but that didn't work, and neither did removing the text from between the "" and leaving it empty. Not sure if that's possible? I guess it's not an urgent need to remove but I think you get trapped since it doesn't do anything if you click it?

**Review by abriggs-usgs — APPROVED** [review]
Seems reasonable step. I'll look at the button once it is merged and make (or make an issue for) any changes that seem warranted.

**Pull request merged**
