### PR TITLE
Add all new enhanced locations tour

### PR DESCRIPTION
**Pull request by abriggs-usgs**
Before making a pull request
----------------------------
First . . .
- [x] Clean the code the way Vue likes it - run 'npm run lint --fix'        
- [x] Make sure all tests run

Then check for accessibly compliance
- [ ] Run WAVE plugin 508 compliance tool

Then run Browserstack; check that application works on . . .
- [ ] Chrome
- [ ] Safari
- [ ] Edge
- [ ] Firefox
- [ ] Samsung Internet
- [ ] Internet Explorer 11 (not supported, but still needs at least a working user redirect page)

Finally . . .
- [x] Update the changelog appropriately

Add New Tour for All New and Enhanced Monitoring Locations
-----------
Made the changes needed to add the new tour.

Not sure why this 'compare changes' is showing changes from an old pull request, but I think it should be fine. (OH, DUH actually I do know why, but it really isn't important and won't change anything)

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the ticket
- [x] Assign someone to review unless the change is trivial

### CODE REVIEW

**Review by mwernimont — APPROVED** [review]

**Comment by mhines-usgs** [comment]
pulling locally to check out! :tada:

**Comment by abriggs-usgs** [comment]
Sorry, hit the merge early. We can revert if you hate

**Review by mhines-usgs — COMMENTED** [review]
sent a note in slack, but i would vote to get rid of the other tours and markers and just have the single tour and markers?

**Comment by mhines-usgs** [comment]
^ talked in person and decided to use the (duh) built-in hide/show layers functionality to achieve this.

**Pull request merged**
